id: ADDB7A8D2
title: colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:41:57.080270
  last_modified_at: 2022-03-01 21:41:57.080276
