id: ADDB7A8D2
title: ยง81-100
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:41:57.118807
  last_modified_at: 2022-03-01 21:41:57.118815
