id: ADDB7A8D2
title: ยง41-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:41:57.105122
  last_modified_at: 2022-03-01 21:41:57.105128
